### ISSUE TITLE
@zh_groups_bot 索引列表中的群链接都指向 bot 自己

### ISSUE THREAD

**Issue by twiceyuan** [wfjsw/osiris-groupindexer#3]
不知道什么时候开始，在 bot 索引请求分类后返回的列表点击之后就无效了，复制链接出来后都是 bot 自己的地址（因为没找到其他反馈渠道先反馈到这里了）

**Comment by wfjsw** [comment]
在安全模式下是这样的，防止有人批量复制链接来发广告。暂时没有关掉这个设置的计划。

**Comment by twiceyuan** [comment]
我意思是指目前 zh_groups_bot 返回的所有群链接都是 @zh_groups_bot，导致点击时都是没有跳转的，这样不是没有办法跳到真正的群了么 😅

<img width="397" alt="Screen Shot 2019-04-07 at 19 29 45" src="https://user-images.githubusercontent.com/2619800/55682904-22ff2f80-596c-11e9-9d9a-59baeb7023bd.png">

**Comment by wfjsw** [comment]
点最下边的 START 会弹一条新消息。

**Comment by twiceyuan** [comment]
感谢……试了下 Android 端确实是这样的，macOS 端的点击后不会显示 START 按钮，估计是客户端出 bug 了……
