### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by wuaidajiejie** [wfjsw/osiris-groupindexer#4]
Error: Cannot find module '../config.ga.json'
大佬请问下这是什么原因呢？

**Comment by wfjsw** [comment]
config.ga.json
```json
{
    "tid": "UA-xxxxxxxxx-x"
}
```

**Comment by wuaidajiejie** [comment]
![IMG_20200721_035451](https://user-images.githubusercontent.com/65920903/87980342-06a5e880-cb06-11ea-9162-bc1ca4d4759d.jpg)

**Comment by wuaidajiejie** [comment]
大佬您好！您的项目缺少这些文件呀！
../resources/quesbank_shzyhxjzg.json
../resources/quesbank_zbzyhxjzg.json
../lib/quesbank

**Comment by wfjsw** [comment]
直接删掉 `/plugins/gpindex_validateuser.js`

**Comment by wuaidajiejie** [comment]
报错了耶
Error: Cannot find module '../lib/quesbank'

**Comment by wfjsw** [comment]
这个也删了 `/plugins/gpindex_ingroupvalidate.js`

**Comment by wuaidajiejie** [comment]
![Screenshot_2020-07-21-17-00-05-740_org telegram messenger](https://user-images.githubusercontent.com/65920903/88034760-bb2a2380-cb73-11ea-8471-e2f09721a654.jpg)

感谢回答，请问下我这是什么情况？
有没有专属于机器人管理员的专属命令呀
没搞明白怎么手动审核用户添加的群组

**Comment by wfjsw** [comment]
这是管理群 就这个样子所以看着就头疼现在不想开了
管理命令看 `gpindex.admin.js`

**Comment by wuaidajiejie** [comment]
不会用呀😓

**Comment by wuaidajiejie** [comment]
玩不来，感谢大佬解答！
