### ISSUE TITLE
继续索引计划

### ISSUE THREAD

**Issue by ghost** [wfjsw/osiris-groupindexer#5]
非常抱歉以这种方式联系您，我找遍了所有能联系到您的方式，无一例外所有方式都得不到回应。
我能够遵守活跃开发、积极维护及非营利，希望继续维护索引计划，已在TG留言，请劳烦您登录TG与我联系。

**Comment by ghost** [comment]
我已自己独立开发了一个TG索引机器人，希望能获得TGCN-群组索引计划Feed频道的使用权，感谢！
TGX-索引秘书：@zh_secretary_bot

**Comment by Hanxv** [comment]
在公益项目中，你需要先做。

当你做到一定程度之后，且还符合项目的初衷，请联系我们。

**Comment by ghost** [comment]
好的，理解，非常感谢！可否提供一下其他联系方式？提ISS怕不是一个好的交流方式。
